import jsPDF from "jspdf";
import "jspdf-autotable";

// Add type support for jspdf-autotable
declare module "jspdf" {
    interface jsPDF {
        autoTable: (options: any) => jsPDF;
    }
}

export interface AuditReportData {
    orgName: string;
    totalItems: number;
    healthScore: number;
    totalLeakage: number;
    totalRecovered?: number;
    findings: any[];
}

export function generateAuditPDF(data: AuditReportData) {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const date = new Date().toLocaleDateString();

    // Header - Premium Look
    doc.setFillColor(15, 15, 15); // Dark background for header
    doc.rect(0, 0, pageWidth, 40, "F");

    doc.setTextColor(255, 255, 255);
    doc.setFontSize(24);
    doc.setFont("helvetica", "bold");
    doc.text("ROYALTY RADAR", 15, 25);

    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text("ENTERPRISE AUDIT SUMMARY", 15, 32);

    doc.setFontSize(10);
    doc.text(`Report Date: ${date}`, pageWidth - 50, 25);

    // Organization Info
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text(`Organization: ${data.orgName}`, 15, 55);

    // Summary Scorecard Row 1
    doc.setFillColor(248, 250, 252);
    doc.rect(15, 65, pageWidth - 30, 30, "F");

    doc.setFontSize(9);
    doc.setTextColor(100, 100, 100);
    doc.setFont("helvetica", "normal");
    doc.text("Catalog Match Rate", 25, 75);
    doc.text("Estimated Revenue Leakage", 80, 75);
    doc.text("Total Audited Items", 150, 75);

    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    if (data.healthScore > 80) {
        doc.setTextColor(16, 185, 129); // Emerald
    } else {
        doc.setTextColor(245, 158, 11); // Amber
    }
    doc.text(`${data.healthScore}%`, 25, 85);

    doc.setTextColor(239, 68, 68); // Rose
    doc.text(`$${data.totalLeakage.toLocaleString(undefined, { minimumFractionDigits: 2 })}`, 80, 85);

    doc.setTextColor(0, 0, 0);
    doc.text(data.totalItems.toString(), 150, 85);

    // Summary Scorecard Row 2 - Financial Recovery
    doc.setFillColor(240, 249, 255); // Light cyan
    doc.rect(15, 100, pageWidth - 30, 25, "F");

    const recovered = data.totalRecovered || 0;
    const recoveryRate = data.totalLeakage > 0 ? (recovered / data.totalLeakage) * 100 : 0;

    doc.setFontSize(9);
    doc.setTextColor(100, 100, 100);
    doc.setFont("helvetica", "normal");
    doc.text("Actually Recovered", 25, 108);
    doc.text("Recovery Efficiency", 80, 108);

    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(16, 185, 129); // Emerald
    doc.text(`$${recovered.toLocaleString(undefined, { minimumFractionDigits: 2 })}`, 25, 118);

    doc.setTextColor(79, 70, 229); // Indigo
    doc.text(`${recoveryRate.toFixed(1)}%`, 80, 118);

    // Detailed Findings Table
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text("Top Anomalies & Conflicts", 15, 140);

    const tableRows = data.findings.map(f => [
        f.type.replace(/_/g, " "),
        f.resourceType,
        f.severity,
        `$${f.estimatedImpact.toFixed(2)}`,
        f.status
    ]);

    doc.autoTable({
        startY: 145,
        head: [['Type', 'Resource', 'Severity', 'Impact', 'Status']],
        body: tableRows,
        theme: 'striped',
        headStyles: { fillColor: [79, 70, 229], textColor: 255 }, // Indigo-600
        alternateRowStyles: { fillColor: [249, 250, 251] },
        styles: { fontSize: 8, cellPadding: 3 },
    });

    // Footer
    const finalY = (doc as any).lastAutoTable.finalY + 20;
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.setFont("helvetica", "italic");
    doc.text("Confidential Report - Generated by RoyaltyRadar AI Engine", pageWidth / 2, finalY, { align: "center" });

    doc.save(`RoyaltyRadar_Audit_${data.orgName.replace(/\s+/g, "_")}_${new Date().toISOString().split('T')[0]}.pdf`);
}
