# Extract all titles from BMI Songview search results (57 performer groupings)
# Data extracted from browser interactive elements

raw_data = """
SADA BABY\t1955\n2055\n+ additional titles
BABY SADA\t1992\n2K 17\n+ additional titles
FMB DZ FEAT SADA BABY\tDOUBLE HEADED DRAGON\nFIELD\n+ additional titles
SORRELL SADA BABY CASADA\t4 SEASONS\nREAL PAIN\n+ additional titles
FMB DZ AND SADA BABY\tDRIPPLE DRAGONS\nTALK MY SHIT
AZCHIKE SADA BABY\tHEAVEN
BANDGANG JIZZLE P JAISWAN SADA BABY\tLICENSE PART 2
BIGKAYBEEZY FEAT SADA BABY\tRED BOTTOMS
BLUEFACE FEATURING ASIAN DOLL GLOKK 9 NLE CHOPPA SADA BABY AND KIDDO CURRY\tTOUR
CRASH RARRI FT SADA BABY\tMELANIN
DAME D O L L A G EAZY SADA BABY\tCHECK REMIX
DAME D O L L A G-EAZY SADA BABY\tCHECK REMIX
E 40 FEAT SADA BABY AND FMB DZ\tPACK ATTACK
E-40 FEAT PAYROLL GIOVANNI FEAT PEEZY FEAT SADA BABY\tI COME FROM THE GAME
EASTSIDE REUP FEAT SADA BABY AND FMB DZ\t762 S FEATURING SADA BABY
FMB DZ AND EASTSIDE REUP FEAT SADA BABY\tFMBROTHAS
FMB DZ FEAT PAPERBOY RELL AND SADA BABY\tWE LOCKED IN\nWHEN THEM APES COMIN
FMB DZ FEAT SADA BABY AND ANTT BEATZ\tONE TIME
HARDWORK JIG AND DAMEDOT FEAT SADA BABY\t100 ROUND
HARDWORK JIGG FEAT SADA BABY\tWAVE
ICEWEAR VEZZO FEAT SADA BABY\tPERFECT
K LOZZ BUX LEE SADA BABY\tIT IS WHAT IT IS
KASH DOLL SADA BABY\tON THE FLO
KRISPYLIFE KIDD ITSMANMAN SADA BABY BENO\tCRAZY LIFE
LARUSSELL EKZAKT AND DTB FEAT SADA BABY\tTEST YA NUTS
MARK WHITE AND SADA BABY\tBREADED
NASAAN FEAT SADA BABY\tDOES IT AGAIN
NEF THE PHARAOH SADA BABY\tLEFT ME IN THE MUD\nLEFT ME IN THE MUD
NOOK TEE GRIZZLEY AND SADA BABY\tDREADZ N BREAD REMIX
NUK SADA BABY\tKRUNXHRAP SUPREME
OBA ROWLAND AND SADA BABY\tRIGHT
OG CEEKAY FT SADA BABY\tACTING\nMURDER
OMB PEEZY SADA BABY\tONE ME
SADA BABY AND BFB DA PACKMAN\tFREE JOE EXOTIC
SADA BABY AND DAMEDOT\tBOKIENA
SADA BABY AND JMSN\tSOFT SPOT 955 REMIX
SADA BABY BIG SEAN HIT BOY\tLITTLE WHILE FEAT BIG SEAN AND HIT BOY
SADA BABY CASADA\tYESTERDAY
SADA BABY CASSADA\tNO GET BACKS
SADA BABY DAMEDOT TID SWEEZE AND VON JOSE\tDAWG IN THE CAR
SADA BABY DREGO AND CHUCHO DABBIN\tWHYTES
SADA BABY FEAT BIG SEAN FEAT HIT BOY\tLITTLE WHILE FEAT BIG SEAN AND HIT BOY
SADA BABY FEAT FMB DZ\tOH BOY
SADA BABY FEAT KAMAIYAH\tCHUCK MONEY
SADA BABY FEAT LAKEYAH\tTO THE MONEY
SADA BABY FEAT SKILLA BABY\tFOOD STAMP FELONS\nJUDY
SADA BABY FT WIZ\tKHALIFA MODE
SADA BABY HOLLOW\tFOE MINUTES OF HELL
SADA BABY SUKIHANA\tSUKISADA
SADA BABY TEE GRIZZLEY\tNEXT UP
SHOOTERGANG KONY SADA BABY\tSHOOT FRONT THE REVEREND
SKILLA BABY SADA BABY\tTIM DUNKIN
TEE GRIZZLEY AND SADA BABY\tGAME\nGRIZZLEY GANG
THECOALCASHCOLLECTION AND SADA BABY\tTHEO RATLIFF
TRIPPE REDD SADA BABY AND ICEWEAR\tCAPTAIN CRUNCH
TRIPPIE REDD SADA BABY ICEWEAR VEZZO BABYFACE\tCAPTAIN CRUNCH
YUNGMANNY FEAT FLO MILLI AND SADA BABY\tCLAP FOR EM
"""

# Extract all unique titles from the visible search results
all_titles = set()
performer_data = []

for line in raw_data.strip().split('\n'):
    if '\t' in line:
        parts = line.split('\t', 1)
        performer = parts[0].strip()
        titles_raw = parts[1].strip()
        titles = [t.strip() for t in titles_raw.split('\n') if t.strip() and t.strip() != '+ additional titles']
        performer_data.append((performer, titles))
        for t in titles:
            all_titles.add(t.upper())

print(f"Total performer groupings: {len(performer_data)}")
print(f"Unique titles visible from search page: {len(all_titles)}")
print()

# Groups with "+ additional titles" that need full catalog extraction
print("Groups with additional titles (need full catalog):")
for performer, titles in performer_data:
    if '+ additional titles' in raw_data.split(performer)[1].split('\n')[0:5]:
        print(f"  - {performer}")

print()
print("All visible titles from search page (sorted):")
for t in sorted(all_titles):
    print(f"  {t}")